### ISSUE TITLE
Suggestion: Blue noise dithering

### ISSUE THREAD

**Issue by ALfuhrmann** [GoergPflug/AttinyStreamGfxApi#2]
You could use [blue noise dithering ](https://momentsingraphics.de/BlueNoise.html)instead of error propagation. 

It needs only a small predefined table and a comparison similar to magic dithering, but provides result at least as good as error propagation. And it does work without context, so you can dither only new parts of an image, without influencing the surrounding pixels.

**Comment by GoergPflug** [comment]
your link is very intresting!
i did a quick google search, and that really looks intresting! i never heard about that....
i will definitely check out if that fits! 64x64 sounds cool, but probably i would have to recalculate the tables myself, to be 1 bit not 2 or three or what they are using, i am not 100% certain, but i will look into that! 

without context is not really needed, because the layers and sprites and consoles , and "calculated plane" are not drawn into a buffer on but the fly directly to the i2c, by optimized code. this saves the memory for the buffer
the engine uses no buffers, and almost no ram, 
about 80 byte or so, the wolfenstein example might in fact run on the attiny 45, as it uses 156 bytes of ram für stack and variables, so i might save away the buffer used for error difusion and save 64 bytes of ram! 
the dithering also method looks intresting, because it should be more stable at fading, also my error difusion is not really that fancy, there are much better implemenations of error diffusion than mine, but is fast....
thanks :)

**Comment by ALfuhrmann** [comment]
Not sure how much memory you can save, but since you could place the blue noise table in PROGMEM, it could work.

If you want to try this, [Gimp ](https://www.gimp.org/)has a blue noise dithering implementation in "Colors/Dither..."

**Comment by ALfuhrmann** [comment]
Not sure how much memory you can save, but since you could place the blue noise table in PROGMEM, it could work.

If you want to try this, [Gimp ](https://www.gimp.org/)has a blue noise dithering implementation in "Colors/Dither..."
