### ISSUE TITLE
ImageCompressorToolForWindows: Can't get it to work

### ISSUE THREAD

**Issue by rbtkarlsson** [GoergPflug/AttinyStreamGfxApi#8]
The tools is generating output, but the generated data only renders as scrambled data. I have also tried with your sample images as source but it generates different output. 

For example: The alley cat using the tools with arguments 0 0 0 17 and file cat1.png turns into this:
255,117,177,190,191,254,62,125,253,3,254,250,251,244,253,245,255,233,251,235.... (shortened)

Instead of as your example where it shows:
31,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255..... (shortened)

Thankful if you can either direct me right if I am using it wrong or look into if you get the same result.

**Comment by GoergPflug** [comment]
Oooops. 
That is my fault, you are using the demos from the v.next folder which contains my work in progress for the upcoming 1.0 . which is much faster and has more features than the original version and will go to the arduino library repo-system. i changed the encoding of the layers which made them 4 times as fast as in the original version.
....
And i forgot to upload my image conversion tool (because it still needed cleanup and dumps loads of debug info)
here it is:
https://github.com/GoergPflug/AttinyStreamGfxApi/tree/main/v.next/layermaker2/LayerMaker2

i tested it with the cat from v.next:
https://wokwi.com/projects/353280465880238081


If you are using the library from the v.next you should be aware that this is a version wich is much faster and has more features than the original version, supports dithering pixels in time so you get real grayscale for consoles and video playback, and filled 3d vector graphics, but contains deep changes and i am right now adapting the samples and the library so every sample works. this is what i am doing in the v.next folder, so the samples in there currently contain different versions of the library that have small changes where i fixed something so everything works with every sample.... this still needs a few rounds of cleanup and documentation before it is ready for 1.0.

If you are using the stuff from v.next you will encounter unfixed bugs for shure, i still needs testing, if you find something or have questions just open a ticket ;-)

thanks for your feedback

**Comment by rbtkarlsson** [comment]
Hi,

Thanks, OK that makes it clear. I have verified it to be working with the LaymerMaker two. 

Tip: In your wokwi demos (love this tool and the demos) there is an option to use the ATTiny85 chip instead of a Arduino Mega board. You need to create a new project and select the ATTiny85 , impossible to change this in a project once selected AFAIK.

See this demo with your 3D rotating cube: https://wokwi.com/projects/353155201365609473

I did find that line drawing for some reason starts from 64,96 and not 0,0 as I had expected, hence the debug info being printed and a diagonal line.

And thanks again for a fine library, looking forward to final version 1.0!

Best,
Robert
